const teamMap={
  "Türkiye":["Galatasaray","Fenerbahçe","Beşiktaş","Trabzonspor","Başakşehir","Adana Demirspor","Samsunspor","Konyaspor"],
  "İngiltere":["Manchester City","Arsenal","Liverpool","Chelsea","Manchester United","Tottenham","Newcastle United","Aston Villa"],
  "İspanya":["Real Madrid","Barcelona","Atletico Madrid","Sevilla","Real Sociedad","Villarreal","Athletic Bilbao","Valencia"],
  "Almanya":["Bayern Münih","Borussia Dortmund","Bayer Leverkusen","RB Leipzig","Stuttgart","Eintracht Frankfurt","Wolfsburg","Freiburg"],
  "İtalya":["Inter","Milan","Juventus","Napoli","Roma","Lazio","Atalanta","Fiorentina"],
  "Fransa":["PSG","Marseille","Monaco","Lyon","Lille","Nice","Rennes","Lens"],
  "Portekiz":["Benfica","Porto","Sporting CP","Braga","Vitoria SC","Boavista"],
  "Hollanda":["Ajax","PSV","Feyenoord","AZ Alkmaar","Twente","Utrecht"],
  "Brezilya":["Flamengo","Palmeiras","Santos","Sao Paulo","Corinthians","Fluminense"],
  "Arjantin":["Boca Juniors","River Plate","Racing Club","Independiente","San Lorenzo","Estudiantes"],
  "Suudi Arabistan":["Al Nassr","Al Hilal","Al Ittihad","Al Ahli","Al Ettifaq"],
  "ABD":["Inter Miami","LA Galaxy","LAFC","New York City","Atlanta United","Seattle Sounders"]
};
const players=[
{name:"Arda Güler",country:"Türkiye",team:"Real Madrid",position:"Orta Saha",value:"45M €",buy:"20M €",sell:"70M €",age:21,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Arda_G%C3%BCler_in_2024_%28cropped%29.jpg/640px-Arda_G%C3%BCler_in_2024_%28cropped%29.jpg",style:"Tekniği, oyun görüşü ve sol ayağıyla dar alanda fark yaratabilen yaratıcı orta saha oyuncusu.",detail:"Arda Güler, hücum hattıyla orta saha arasında bağlantı kuran, topu ayağına aldığında oyunun yönünü değiştirebilen özel bir profil. Pas kalitesi, şut tehdidi ve duran top becerisi onu genç yaşına rağmen üst seviye maçlarda dikkat çeken bir oyuncu haline getiriyor. Düzenli süre buldukça piyasa değerinin ve performans etkisinin artması beklenir.",perf:"Son dönemde süre aldığı maçlarda yaratıcılık, kilit pas ve ceza sahası çevresi şut tehdidiyle öne çıkıyor.",transfers:[["2023/24","Fenerbahçe","Real Madrid","20M €"],["2021/22","Gençlerbirliği","Fenerbahçe","Bedelsiz"]]},
{name:"Kenan Yıldız",country:"Türkiye",team:"Juventus",position:"Forvet",value:"40M €",buy:"0.5M €",sell:"65M €",age:21,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Kenan_Y%C4%B1ld%C4%B1z_2023.jpg/640px-Kenan_Y%C4%B1ld%C4%B1z_2023.jpg",style:"Kanattan içeri kat eden, bire birde cesur ve bitiriciliği gelişen hücum oyuncusu.",detail:"Kenan Yıldız, modern futbolda kanat-forvet rolüne uygun, topu taşıyan ve savunma arkasına koşular atan bir futbolcu. Genç yaşına rağmen karar kalitesi gelişiyor; özellikle büyük maçlarda sorumluluk almaktan kaçınmayan yapısıyla öne çıkıyor.",perf:"Hücumda hareketlilik, adam eksiltme ve ceza sahasına girişleriyle takımına enerji katıyor.",transfers:[["2022/23","Bayern Münih U19","Juventus","Serbest"],["2012/13","Altyapı","Bayern Münih","-"]]},
{name:"Kylian Mbappé",country:"Fransa",team:"Real Madrid",position:"Forvet",value:"180M €",buy:"Serbest",sell:"200M €",age:27,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Kylian_Mbapp%C3%A9_2019.jpg/640px-Kylian_Mbapp%C3%A9_2019.jpg",style:"Hızı, bitiriciliği ve savunma arkası koşularıyla dünyanın en etkili forvetlerinden.",detail:"Mbappé, oyunun temposunu tek koşuyla değiştirebilen elit bir hücum oyuncusu. Açık alanda çok tehlikeli olmasının yanında, ceza sahası içinde bitiricilik ve pozisyon alma kalitesiyle de fark yaratır. Büyük maç tecrübesi ve marka değeri piyasa değerini yüksek tutan temel faktörlerdir.",perf:"Gol katkısı, sprint kalitesi ve savunma arkasına yaptığı koşularla takımın ana skor tehdidi.",transfers:[["2024/25","PSG","Real Madrid","Serbest"],["2018/19","Monaco","PSG","180M €"]]},
{name:"Erling Haaland",country:"Norveç",team:"Manchester City",position:"Forvet",value:"180M €",buy:"60M €",sell:"210M €",age:25,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Erling_Haaland_2023_%28cropped%29.jpg/640px-Erling_Haaland_2023_%28cropped%29.jpg",style:"Ceza sahası içi bitiriciliği, fizik gücü ve koşu zamanlamasıyla elit santrfor.",detail:"Haaland, modern santrfor rolünün en güçlü örneklerinden biri. Az temasla gol pozisyonuna girer, savunmacıların arkasına doğru zamanda koşar ve ceza sahasında çok yüksek yüzdeyle bitirir. Takımı topa sahip olduğunda merkezde sürekli tehdit oluşturur.",perf:"Maç başına gol tehdidi, hava topları ve ceza sahası koşuları en belirgin özellikleri.",transfers:[["2022/23","Borussia Dortmund","Manchester City","60M €"],["2020/21","Salzburg","Borussia Dortmund","20M €"]]},
{name:"Jude Bellingham",country:"İngiltere",team:"Real Madrid",position:"Orta Saha",value:"180M €",buy:"103M €",sell:"200M €",age:23,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Jude_Bellingham_2022.jpg/640px-Jude_Bellingham_2022.jpg",style:"Box-to-box enerjisi, skor katkısı ve liderliğiyle oyunun iki yönünde etkili.",detail:"Bellingham, orta sahada fizik gücü, oyun zekası ve ceza sahasına geç koşularıyla fark yaratır. Sadece pas istasyonu değil, aynı zamanda skor üreten ve pres gücüyle rakibi bozan bir oyuncu profilidir.",perf:"Top kazanma, hücum koşuları ve maç ritmini yükseltme konusunda çok değerli.",transfers:[["2023/24","Borussia Dortmund","Real Madrid","103M €"],["2020/21","Birmingham","Borussia Dortmund","25M €"]]},
{name:"Vinícius Júnior",country:"Brezilya",team:"Real Madrid",position:"Forvet",value:"150M €",buy:"45M €",sell:"180M €",age:25,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Vin%C3%ADcius_J%C3%BAnior_2021.jpg/640px-Vin%C3%ADcius_J%C3%BAnior_2021.jpg",style:"Sol kanatta hız, bire bir ve derin koşularla maç kıran hücumcu.",detail:"Vinícius Júnior, açık alanda durdurulması zor bir kanat oyuncusu. Bire birde adam eksiltir, çizgiden içeri girerek şut veya asist üretir. Büyük maçlarda aldığı sorumluluk ve sürekli tehdit oluşturması onu elit seviyeye taşır.",perf:"Dripling, hız ve savunma arkasına koşularla hücumda ana tehditlerden biri.",transfers:[["2018/19","Flamengo","Real Madrid","45M €"]]},
{name:"Victor Osimhen",country:"Nijerya",team:"Galatasaray",position:"Forvet",value:"100M €",buy:"Kiralık",sell:"120M €",age:27,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Victor_Osimhen_2022.jpg/640px-Victor_Osimhen_2022.jpg",style:"Fizik gücü, presi, hava topu ve bitiriciliğiyle komple santrfor.",detail:"Osimhen, savunma hattını sürekli rahatsız eden, pres yapan ve ceza sahasında güçlü kalan bir forvet. Hem geçiş oyununda hem yerleşik hücumda takımına net hedef oyuncu rolü sağlar. Büyük fiziksel kapasitesi onu transfer gündeminin önemli isimlerinden yapar.",perf:"Gol tehdidi, hava topları ve rakip savunmayı yıpratma gücüyle öne çıkar.",transfers:[["2024/25","Napoli","Galatasaray","Kiralık"],["2020/21","Lille","Napoli","75M €"]]},
{name:"Lamine Yamal",country:"İspanya",team:"Barcelona",position:"Forvet",value:"120M €",buy:"Altyapı",sell:"180M €",age:19,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Lamine_Yamal_2024.jpg/640px-Lamine_Yamal_2024.jpg",style:"Sağ kanattan içeri kat eden, pas açısı bulan ve bire birde etkili genç yıldız.",detail:"Lamine Yamal, yaşına rağmen çok olgun kararlar verebilen teknik bir kanat oyuncusu. Rakibi üstüne çekip pas açısı oluşturması, dar alanda sakince çözüm üretmesi ve yaratıcı oyun aklı onu özel kılıyor.",perf:"Bire bir, kilit pas ve ceza sahası çevresinde yaratıcılık üretimi yüksek.",transfers:[["2023/24","Barcelona U19","Barcelona","Altyapı"]]},
{name:"Harry Kane",country:"İngiltere",team:"Bayern Münih",position:"Forvet",value:"90M €",buy:"100M €",sell:"95M €",age:32,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Harry_Kane_in_Russia_2.jpg/640px-Harry_Kane_in_Russia_2.jpg",style:"Bitirici santrfor, oyun kurucu pas kalitesi ve ceza sahası sezgisiyle etkili.",detail:"Harry Kane sadece gol atan değil, aynı zamanda geriye gelip oyunu kurabilen bir forvet. Pas kalitesiyle kanat oyuncularını pozisyona sokar ve ceza sahasında bitirici vuruşlarıyla güven verir.",perf:"Gol, asist ve bağlantı oyunundaki katkısıyla hücum merkezinde kilit rol oynar.",transfers:[["2023/24","Tottenham","Bayern Münih","100M €"]]},
{name:"Lautaro Martínez",country:"Arjantin",team:"Inter",position:"Forvet",value:"110M €",buy:"25M €",sell:"125M €",age:28,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Lautaro_Martinez_2022.jpg/640px-Lautaro_Martinez_2022.jpg",style:"Ceza sahası hareketliliği, presi ve güçlü bitiriciliğiyle lider forvet.",detail:"Lautaro Martínez, savunmaya baskı yapan ve ceza sahasında doğru pozisyon alan bir hücum lideri. Takım oyununa katılır, ikili mücadelelerde dirençli kalır ve kritik anlarda skor üretir.",perf:"Pres gücü, bitiricilik ve takım liderliğiyle Inter hücumunun merkezi.",transfers:[["2018/19","Racing Club","Inter","25M €"]]},
{name:"Cristiano Ronaldo",country:"Portekiz",team:"Al Nassr",position:"Forvet",value:"15M €",buy:"Serbest",sell:"20M €",age:41,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cristiano_Ronaldo_2018.jpg/640px-Cristiano_Ronaldo_2018.jpg",style:"Bitiricilik, hava topları ve profesyonel disiplinle gol tehdidi oluşturan yıldız.",detail:"Cristiano Ronaldo, kariyeri boyunca gol içgüdüsü ve fiziksel hazırlığıyla fark yarattı. Ceza sahasında pozisyon alma, hava topları ve final vuruşları halen en güçlü yanları arasında.",perf:"Gol sezgisi, liderlik ve ceza sahası bitiriciliğiyle takımına değer katar.",transfers:[["2022/23","Manchester United","Al Nassr","Serbest"],["2021/22","Juventus","Manchester United","15M €"]]},
{name:"Lionel Messi",country:"Arjantin",team:"Inter Miami",position:"Forvet",value:"20M €",buy:"Serbest",sell:"25M €",age:39,img:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Lionel_Messi_20180626.jpg/640px-Lionel_Messi_20180626.jpg",style:"Oyun aklı, pas, şut ve dar alan becerisiyle futbol tarihinin en özel oyuncularından.",detail:"Messi, oyunu okuma becerisi, pas açıları ve dar alanda top saklama kalitesiyle takımın hücum aklını oluşturur. Yaşı ilerlese de duran top, final pası ve şut kalitesiyle maçların kaderini değiştirebilir.",perf:"Yaratıcılık, asist, duran top ve son pas kalitesiyle fark yaratır.",transfers:[["2023/24","PSG","Inter Miami","Serbest"],["2021/22","Barcelona","PSG","Serbest"]]}
];
const baseNews=[
{type:"Transfer Gündemi",title:"Avrupa devleri genç yıldızlar için yarışta",text:"Yaz transfer dönemine yaklaşılırken kulüpler, genç ve yüksek potansiyelli futbolcular için erkenden temas kurmaya başladı. Özellikle orta saha ve kanat oyuncularında piyasa hareketliliği bekleniyor.",img:"https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1100&q=80"},
{type:"Futbol Haberleri",title:"Teknik direktörler yeni sezon planlarını şekillendiriyor",text:"Büyük liglerde takımlar kadro derinliği, pres gücü ve hücum varyasyonlarını artırmak için hazırlıklarını sürdürüyor. Taraftarların gözü transfer listelerinde ve kamp performanslarında.",img:"https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1100&q=80"},
{type:"Maç Gündemi",title:"Derbi haftasında yıldız futbolcular sahneye çıkıyor",text:"Haftanın önemli karşılaşmalarında gözler hücum oyuncuları ve kalecilerde olacak. Form grafiği yükselen futbolcuların performansı, şampiyonluk ve Avrupa yarışı için belirleyici olabilir.",img:"https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1100&q=80"},
{type:"Futbolcu Haberleri",title:"Genç yeteneklerin piyasa değeri yükselişte",text:"Avrupa'nın önde gelen liglerinde süre bulan genç futbolcular, performanslarıyla transfer piyasasında öne çıkıyor. Kulüpler uzun vadeli yatırım için bu oyuncuları yakından takip ediyor.",img:"https://images.unsplash.com/photo-1556056504-5c7696c4c28d?auto=format&fit=crop&w=1100&q=80"},
{type:"Transfer Gündemi",title:"Forvet arayan takımlar golcü listesini genişletti",text:"Sezon boyunca bitiricilik sorunu yaşayan kulüpler, yeni dönemde güçlü bir santrfor transferi için çalışmalarını hızlandırdı. Gol katkısı yüksek oyuncuların fiyatı artabilir.",img:"https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1100&q=80"}
];
let news=[...baseNews], newsIndex=0, featuredIndex=0;
function valueNumber(v){ if(!v) return 0; const clean=String(v).replace(',','.'); const n=parseFloat(clean); if(/M/i.test(clean)) return n*1000000; if(/K/i.test(clean)) return n*1000; return isNaN(n)?0:n; }
function featuredPlayersByValue(){ return [...players].sort((a,b)=>valueNumber(b.value)-valueNumber(a.value)); }
function el(id){return document.getElementById(id)}
function allTeams(){return Object.values(teamMap).flat()}
function setup(){
  el('countryCount').textContent=Object.keys(teamMap).length; el('teamCount').textContent=allTeams().length; el('playerCount').textContent=players.length;
  const country=el('country'); country.innerHTML='<option value="all">Tüm Ülkeler</option>'+Object.keys(teamMap).map(c=>`<option>${c}</option>`).join('');
  fillTeams(); renderPlayers(); renderNews(); renderSmallNews(); renderFeatured();
  setInterval(nextNews,5500); setInterval(nextFeatured,10000); fetchFootballNews();
}
function fillTeams(){const c=el('country').value; const teams=c==='all'?allTeams():teamMap[c]||[]; el('team').innerHTML='<option value="all">Tüm Takımlar</option>'+teams.map(t=>`<option>${t}</option>`).join(''); renderTeamList(teams)}
function countryChanged(){fillTeams(); renderPlayers()}
function renderTeamList(teams){el('teamList').innerHTML=teams.map(t=>`<div class="teamItem"><span>${t}</span><small>${players.filter(p=>p.team===t).length} futbolcu</small></div>`).join('')||'<p style="color:var(--muted)">Takım bulunamadı.</p>'}
function renderPlayers(){
  const q=el('search').value.toLowerCase().trim(), c=el('country').value, t=el('team').value, pos=el('position').value;
  let list=players.filter(p=>(c==='all'||p.country===c)&&(t==='all'||p.team===t)&&(pos==='all'||p.position===pos)&&(!q||[p.name,p.country,p.team,p.position].join(' ').toLowerCase().includes(q)));
  el('players').innerHTML=list.map((p,i)=>`<article class="playerCard" onclick="openPlayer('${p.name.replaceAll("'","\\'")}')"><div class="photo"><img src="${p.img}" onerror="this.src='https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=80'"><span class="badge">${p.country}</span><span class="value">${p.value}</span></div><div class="cardBody"><h3>${p.name}</h3><div class="meta"><span>${p.team}</span><span>${p.position}</span><span>${p.age} yaş</span></div><p class="desc">${p.style}</p></div><div class="cardFoot"><span>Alış: ${p.buy}</span><span>Detayları aç →</span></div></article>`).join('') || '<div class="box"><h3>Sonuç yok</h3><p style="color:var(--muted)">Bu filtrelerde futbolcu bulunamadı.</p></div>';
}
function renderFeatured(){const ranked=featuredPlayersByValue(); const p=ranked[featuredIndex%ranked.length]; el('featuredPlayer').innerHTML=`<img src="${p.img}" onerror="this.src='https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=80'"><div><h3>${p.name}</h3><p>${p.detail.slice(0,180)}...</p><div class="chips"><span class="chip">${p.team}</span><span class="chip">${p.position}</span><span class="chip">${p.value}</span><span class="chip">10 sn</span></div></div>`}
function nextFeatured(){const ranked=featuredPlayersByValue(); featuredIndex=(featuredIndex+1)%ranked.length; renderFeatured()}
function renderNews(){const n=news[newsIndex%news.length]; el('newsCard').innerHTML=`<div class="newsImage"><img src="${n.img}" onerror="this.src='https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1100&q=80'"></div><div class="newsContent"><span class="newsType">${n.type}</span><h2>${n.title}</h2><p>${n.text}</p>${n.link?`<p class="source"><a href="${n.link}" target="_blank" rel="noopener">Haberi aç</a></p>`:''}</div>`; el('newsDots').innerHTML=news.map((_,i)=>`<span class="ndot ${i===newsIndex?'active':''}"></span>`).join(''); el('newsSource').innerHTML=n.link?'<a target="_blank" rel="noopener" href="'+n.link+'">Kaynağa git</a>':'Futbol haberleri'; renderSmallNews()}
function renderSmallNews(){let cards=[1,2,3].map(x=>news[(newsIndex+x)%news.length]); el('smallNews').innerHTML=cards.map(n=>`<article><b>${n.title}</b><span>${n.text.slice(0,115)}...</span></article>`).join('')}
function nextNews(){newsIndex=(newsIndex+1)%news.length; renderNews()} function prevNews(){newsIndex=(newsIndex-1+news.length)%news.length; renderNews()}
async function fetchFootballNews(){
  try{const url='https://api.allorigins.win/raw?url='+encodeURIComponent('https://news.google.com/rss/search?q=futbol%20transfer%20football%20soccer&hl=tr&gl=TR&ceid=TR:tr'); const res=await fetch(url); if(!res.ok) throw new Error('rss'); const txt=await res.text(); const doc=new DOMParser().parseFromString(txt,'text/xml'); const items=[...doc.querySelectorAll('item')].slice(0,6).map((it,i)=>({type:i%2?'Futbol Haberleri':'Transfer Gündemi',title:it.querySelector('title')?.textContent.replace(/ - .+$/,'')||'Futbol haberi',text:'Futbol gündeminden otomatik çekilen haber. Detayları okumak için kaynak bağlantısını açabilirsiniz.',link:it.querySelector('link')?.textContent,img:baseNews[i%baseNews.length].img})); if(items.length){news=[...items,...baseNews]; newsIndex=0; renderNews();}}
  catch(e){console.log('Haber çekilemedi, hazır futbol haberleri gösteriliyor.')}
}
function openPlayer(name){const p=players.find(x=>x.name===name); const saved=JSON.parse(localStorage.getItem('comments_'+p.name)||'[]'); el('modalBox').innerHTML=`<div class="modalTop"><img src="${p.img}" onerror="this.src='https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=80'"><div class="detail"><span class="tag">${p.country} · ${p.team}</span><h2>${p.name}</h2><p>${p.detail}</p><div class="gridInfo"><div class="info"><small>Mevki</small><b>${p.position}</b></div><div class="info"><small>Piyasa Değeri</small><b>${p.value}</b></div><div class="info"><small>Alış Fiyatı</small><b>${p.buy}</b></div><div class="info"><small>Satış Beklentisi</small><b>${p.sell}</b></div><div class="info"><small>Yaş</small><b>${p.age}</b></div><div class="info"><small>Performans</small><b>Yükselişte</b></div></div><h3>Performans Açıklaması</h3><p>${p.perf}</p><h3>Transfer Geçmişi</h3><table class="table"><thead><tr><th>Sezon</th><th>Eski Takım</th><th>Yeni Takım</th><th>Ücret</th></tr></thead><tbody>${p.transfers.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('')}</tbody></table></div></div><div class="comments"><h3>Yorumlar</h3><div class="commentForm"><input id="commentInput" placeholder="Bu futbolcu hakkında yorum yaz..."><button class="btn" onclick="addComment('${p.name.replaceAll("'","\\'")}')">Gönder</button></div><div class="commentList" id="commentList">${saved.map(c=>`<div class="comment">${c}</div>`).join('')||'<div class="comment">Henüz yorum yok. İlk yorumu sen yaz.</div>'}</div></div>`; el('modal').classList.add('show')}

function showFeedbackPopup(){const f=el('feedbackOverlay'); if(f) f.classList.add('show')}
function closeFeedback(){const f=el('feedbackOverlay'); if(f) f.classList.remove('show')}
function showFeedbackForm(){el('feedbackForm').classList.add('show'); el('saveFeedbackBtn').style.display='inline-flex'; el('openFeedbackBtn').style.display='none'; setTimeout(()=>el('feedbackText').focus(),80)}
function saveFeedback(){const txt=el('feedbackText').value.trim(); if(txt){const list=JSON.parse(localStorage.getItem('site_feedback')||'[]'); list.unshift({text:txt,date:new Date().toLocaleString('tr-TR')}); localStorage.setItem('site_feedback',JSON.stringify(list.slice(0,20))); el('feedbackText').value=''; el('feedbackNote').style.display='block'} else {el('feedbackNote').textContent='Boş görüş kaydedilmedi. İsterseniz kapatabilirsiniz.'; el('feedbackNote').style.display='block'} }
function hasBlockedWords(text){return /(a\s*m\s*k|s\s*i\s*k|o\s*ç|p\s*i\s*ç|g\s*e\s*r\s*i\s*z\s*e\s*k\s*a\s*l\s*ı|m\s*a\s*l\b|salak|aptal)/i.test(text)}
function closeModal(){el('modal').classList.remove('show')} function addComment(name){const input=el('commentInput'); const v=input.value.trim(); if(!v)return; if(v.length>240){alert('Yorum en fazla 240 karakter olabilir.');return} if(hasBlockedWords(v)){alert('Küfürlü, argo veya hakaret içeren yorumlar kaydedilemez.');return} const safe=v.replace(/[<>]/g,''); const key='comments_'+name; const arr=JSON.parse(localStorage.getItem(key)||'[]'); arr.unshift(safe); localStorage.setItem(key,JSON.stringify(arr)); input.value=''; openPlayer(name)}
window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeFeedback();}}); setup(); setTimeout(showFeedbackPopup,550);
